# TODO: implement build script :)

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: "Run a one-line script"

- script: echo Should run a build script here :)
  displayName: "Run build script"
