# TODO: make this better
# Should create legit pipeline instead of using batch files

trigger:
- master

pool:
  vmImage: windows-2019

steps:
- script: .\Scripts\BuildClient.bat
  displayName: "Build Client on Windows"
